BULLETTRAIN_PROMPT_ORDER=(
    time
    dir
    git
    cmd_exec_time
    status
)

BULLETTRAIN_TIME_BG=blue
BULLETTRAIN_PROMPT_CHAR=▶
BULLETTRAIN_DIR_FG=black
BULLETTRAIN_DIR_BG=005
BULLETTRAIN_GIT_BG=015white
BULLETTRAIN_GIT_UNTRACKED="%F{009}★%F{black}"    
