BULLETTRAIN_PROMPT_ORDER=(
    time
    dir
    git
    cmd_exec_time
    status
)

BULLETTRAIN_TIME_BG=red
BULLETTRAIN_PROMPT_CHAR="%F{cyan}▶"
BULLETTRAIN_DIR_FG=black
BULLETTRAIN_DIR_BG=blue
BULLETTRAIN_GIT_BG=white
BULLETTRAIN_GIT_UNTRACKED="%F{009}★%F{black}"    
BULLETTRAIN_STATUS_ERROR_BG=magenta
