#!/usr/bin/env python3
#
# Copyright (C) 2016 James Murphy
# Copyright (C) 2017 Trevor Vannoy
# Licensed under the GPL version 2 only
#
# A battery indicator blocklet script for i3blocks

from subprocess import check_output

status = check_output(['acpi'], universal_newlines=True)

if not status:
    # stands for no battery found
    fulltext = "<span color='red'><span font='Font Awesome 5 Free'>\uf00d \uf240</span></span>"
    percentleft = 100
else:
    # if there is more than one battery in one laptop, the percentage left is 
    # available for each battery separately, although state and remaining 
    # time for overall block is shown in the status of the first battery 
    batteries = status.split("\n")
    state_batteries=[]
    commasplitstatus_batteries=[]
    percentleft_batteries=[]
    for battery in batteries:
        if battery!='':
            state_batteries.append(battery.split(": ")[1].split(", ")[0])
            commasplitstatus = battery.split(", ")
            percentleft_batteries.append(int(commasplitstatus[1].rstrip("%\n")))
            commasplitstatus_batteries.append(commasplitstatus)
    state = state_batteries[0]
    commasplitstatus = commasplitstatus_batteries[0]
    percentleft = int(sum(percentleft_batteries)/len(percentleft_batteries))

    # stands for charging
    FA_LIGHTNING = "<span color='#f0c674'><span font='Font Awesome 5 Free'>\uf0e7</span></span>"

    # stands for plugged in
    FA_PLUG = "<span font='Font Awesome 5 Free'>\uf1e6</span>"

    # stands for using battery
    FA_BATTERY_FULL = "<span font='Font Awesome 5 Free'>\uf240</span>"
    FA_BATTERY_THREE_QUARTERS = "<span font='Font Awesome 5 Free'>\uf241</span>"
    FA_BATTERY_HALF = "<span font='Font Awesome 5 Free'>\uf242</span>"
    FA_BATTERY_QUARTER = "<span font='Font Awesome 5 Free'>\uf243</span>"
    FA_BATTERY_EMPTY = "<span font='Font Awesome 5 Free'>\uf244</span>"

    # stands for unknown status of battery
    FA_QUESTION = "<span font='Font Awesome 5 Free'>\uf128</span>"

    timeleft = ""

    if state == "Discharging":
        time = commasplitstatus[-1].split()[0]
        time = ":".join(time.split(":")[0:2])
        timeleft = " ({})".format(time)
        if percentleft < 15:
            fulltext = FA_BATTERY_EMPTY + " "
        elif percentleft < 25:
            fulltext = FA_BATTERY_QUARTER + " "
        elif percentleft < 50:
            fulltext = FA_BATTERY_HALF + " "
        elif percentleft < 75:
            fulltext = FA_BATTERY_THREE_QUARTERS + " "
        else:
            fulltext = FA_BATTERY_FULL + " "
    elif state == "Full":
        fulltext = FA_PLUG + " "
    elif state == "Unknown":
        fulltext = FA_QUESTION + " " + FA_BATTERY + " "
    else:
        fulltext = FA_LIGHTNING + " " + FA_PLUG + " "


    form =  '<span color="{}">{}%</span>'
    fulltext += str(percentleft) + '%'
    fulltext += timeleft

print(fulltext)
print(fulltext)
if percentleft < 10:
    exit(33)
