#!/bin/bash
# Licensed under the terms of the GNU GENERAL PUBLIC LICENSE v2, or any later version.


# date pattern, more at 'man date'
DATE_PATTERN="%d/%m %H:%M "

#
# command after clicking
#

CAL="${BLOCK_INSTANCE:-gsimplecal}"

#---------------------------------------------------------------

if [ "${BLOCK_BUTTON}" == "1" ]; then
	eval "i3-msg -q 'exec --no-startup-id $CAL'"
        
fi

date +"$DATE_PATTERN"
