#!/usr/bin/env bash

################################
# Shows info about sound/volume.
# Allows simple volume controls.
#
# Thanks to [@EliteTK](https://gist.github.com/EliteTK/36d061fa24372fb70312),
# for the big speed gain when switching to `ponymix`
#
# Dependencies:
# - ponymix
# - ttf-font-awesome
#
# @return {Number}: Current volume
################################

full=""
short=""
status=0

step=${BLOCK_INSTANCE:-5}

getVolume() {
	ponymix get-volume
}

isMuted() {
	ponymix is-muted
}


vol=$(getVolume)

# level-based icon
if (( $vol == 0 )); then
	icon=""
elif (( $vol < 50 )); then
	icon=""
else
	icon=""
fi

# determine mute status
if isMuted; then
	icon=""
	#status=33
fi

full="$icon $vol%"
short=$vol

echo $full
echo $short
exit $status
