#!/usr/bin/perl

# File generated by menutray v0.48

# DO NOT edit this file!
# Any change in this file will be lost!
# Edit '/home/bugsbunny/.config/menutray/schema.pl' instead!

use utf8;
use strict;
use Gtk2 ('-init');

my $menu = 'Gtk2::Menu'->new;
my $icon = 'Gtk2::StatusIcon'->new;

$icon->set_from_icon_name('start-here-archlinux');
$icon->set_visible(1);
$icon->signal_connect('button-release-event', \&show_icon_menu);

load_menu();

sub show_icon_menu {
    $menu->popup(undef, undef, sub {return Gtk2::StatusIcon::position_menu($menu, 0, 0, $icon)}, [1, 1], 0, 0);
    return 1;
}

sub load_menu {

    # # # # # # # # # # # # # # # # # # # # ACCESSORIES # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Accessories");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-utilities",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("About\ Xfce");
    $app->signal_connect('activate', sub {system "xfce4\-about &"});
    $app->set_property('tooltip_text', "Information\ about\ the\ Xfce\ Desktop\ Environment");
    $app->set_image('Gtk2::Image'->new_from_icon_name("help\-about",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Archive\ Manager");
    $app->signal_connect('activate', sub {system "file\-roller &"});
    $app->set_property('tooltip_text', "Create\ and\ modify\ an\ archive");
    $app->set_image('Gtk2::Image'->new_from_icon_name("file\-roller",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Atom");
    $app->signal_connect('activate', sub {system "electron\ \-\-app\=\/usr\/lib\/atom &"});
    $app->set_property('tooltip_text', "A\ hackable\ text\ editor\ for\ the\ 21st\ Century");
    $app->set_image('Gtk2::Image'->new_from_icon_name("atom",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Bulk\ Rename");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/Thunar\/ThunarBulkRename &"});
    $app->set_property('tooltip_text', "Rename\ Multiple\ Files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("Thunar",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("File\ Manager");
    $app->signal_connect('activate', sub {system "exo\-open\ \-\-launch\ FileManager &"});
    $app->set_property('tooltip_text', "Browse\ the\ file\ system");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Files");
    $app->signal_connect('activate', sub {system "nautilus\ \-\-new\-window &"});
    $app->set_property('tooltip_text', "Access\ and\ organize\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("org\.gnome\.Nautilus",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("HP\ Device\ Manager");
    $app->signal_connect('activate', sub {system "hp\-toolbox &"});
    $app->set_property('tooltip_text', "View\ device\ status\,\ ink\ levels\ and\ perform\ maintenance\.");
    $app->set_image('Gtk2::Image'->new_from_pixbuf('Gtk2::Gdk::Pixbuf'->new_from_file_at_size("\/usr\/share\/hplip\/data\/images\/128x128\/hp_logo\.png",16,16)));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("KeePass\ Password\ Safe");
    $app->signal_connect('activate', sub {system "keepass &"});
    $app->set_property('tooltip_text', "The\ free\,\ open\ source\,\ light\-weight\ and\ easy\-to\-use\ password\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("keepass",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Nemo");
    $app->signal_connect('activate', sub {system "nemo &"});
    $app->set_property('tooltip_text', "Access\ and\ organize\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("folder",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Redshift");
    $app->signal_connect('activate', sub {system "redshift\-gtk &"});
    $app->set_property('tooltip_text', "Color\ temperature\ adjustment\ tool");
    $app->set_image('Gtk2::Image'->new_from_icon_name("redshift",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("SpeedCrunch");
    $app->signal_connect('activate', sub {system "speedcrunch &"});
    $app->set_property('tooltip_text', "A\ high\-precision\ scientific\ calculator");
    $app->set_image('Gtk2::Image'->new_from_icon_name("speedcrunch",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Terminal\ Emulator");
    $app->signal_connect('activate', sub {system "exo\-open\ \-\-launch\ TerminalEmulator &"});
    $app->set_property('tooltip_text', "Use\ the\ command\ line");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Terminator");
    $app->signal_connect('activate', sub {system "terminator &"});
    $app->set_property('tooltip_text', "Multiple\ terminals\ in\ one\ window");
    $app->set_image('Gtk2::Image'->new_from_icon_name("terminator",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Thunar\ File\ Manager");
    $app->signal_connect('activate', sub {system "thunar &"});
    $app->set_property('tooltip_text', "Browse\ the\ filesystem\ with\ the\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("Thunar",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # DEVELOPMENT # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Development");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-development",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Arduino\ IDE");
    $app->signal_connect('activate', sub {system "arduino &"});
    $app->set_property('tooltip_text', "Open\-source\ electronics\ prototyping\ platform");
    $app->set_image('Gtk2::Image'->new_from_icon_name("arduino",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Atom");
    $app->signal_connect('activate', sub {system "electron\ \-\-app\=\/usr\/lib\/atom &"});
    $app->set_property('tooltip_text', "A\ hackable\ text\ editor\ for\ the\ 21st\ Century");
    $app->set_image('Gtk2::Image'->new_from_icon_name("atom",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("CMake");
    $app->signal_connect('activate', sub {system "cmake\-gui &"});
    $app->set_property('tooltip_text', "Cross\-platform\ buildsystem");
    $app->set_image('Gtk2::Image'->new_from_icon_name("CMakeSetup",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Electron");
    $app->signal_connect('activate', sub {system "electron &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("electron",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("OpenJDK\ 1\.7\.0\ Monitoring\ \&\ Management\ Console");
    $app->signal_connect('activate', sub {system "_BINDIR_\/jconsole &"});
    $app->set_property('tooltip_text', "Monitor\ and\ manage\ OpenJDK\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("java\-1\.7\.0",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("OpenJDK\ 1\.7\.0\ Policy\ Tool");
    $app->signal_connect('activate', sub {system "_BINDIR_\/policytool &"});
    $app->set_property('tooltip_text', "Manage\ OpenJDK\ policy\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("java\-1\.7\.0",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt4\ Assistant");
    $app->signal_connect('activate', sub {system "assistant\-qt4 &"});
    $app->set_property('tooltip_text', "Shows\ Qt4\ documentation\ and\ examples");
    $app->set_image('Gtk2::Image'->new_from_icon_name("assistant\-qt4",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt4\ Designer");
    $app->signal_connect('activate', sub {system "designer\-qt4 &"});
    $app->set_property('tooltip_text', "Design\ GUIs\ for\ Qt4\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("designer\-qt4",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt4\ Linguist");
    $app->signal_connect('activate', sub {system "linguist\-qt4 &"});
    $app->set_property('tooltip_text', "Add\ translations\ to\ Qt4\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("linguist\-qt4",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt4\ QDbusViewer");
    $app->signal_connect('activate', sub {system "qdbusviewer\-qt4 &"});
    $app->set_property('tooltip_text', "Debug\ D\-Bus\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qdbusviewer\-qt4",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ Assistant");
    $app->signal_connect('activate', sub {system "assistant &"});
    $app->set_property('tooltip_text', "Shows\ Qt\ documentation\ and\ examples");
    $app->set_image('Gtk2::Image'->new_from_icon_name("assistant",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ Designer");
    $app->signal_connect('activate', sub {system "designer &"});
    $app->set_property('tooltip_text', "Design\ GUIs\ for\ Qt\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("QtProject\-designer",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ Linguist");
    $app->signal_connect('activate', sub {system "linguist &"});
    $app->set_property('tooltip_text', "Add\ translations\ to\ Qt\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("linguist",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ QDbusViewer");
    $app->signal_connect('activate', sub {system "qdbusviewer &"});
    $app->set_property('tooltip_text', "Debug\ D\-Bus\ applications");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qdbusviewer",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # EDUCATION # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Education");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-science",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Math");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-math &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ scientific\ formulas\ and\ equations\ by\ using\ Math\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-math",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # GRAPHICS # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Graphics");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-graphics",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Blender");
    $app->signal_connect('activate', sub {system "blender &"});
    $app->set_property('tooltip_text', "3D\ modeling\,\ animation\,\ rendering\ and\ post\-production");
    $app->set_image('Gtk2::Image'->new_from_icon_name("blender",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Document\ Viewer");
    $app->signal_connect('activate', sub {system "evince &"});
    $app->set_property('tooltip_text', "View\ multi\-page\ documents");
    $app->set_image('Gtk2::Image'->new_from_icon_name("evince",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("GNU\ Image\ Manipulation\ Program");
    $app->signal_connect('activate', sub {system "gimp\-2\.8 &"});
    $app->set_property('tooltip_text', "Create\ images\ and\ edit\ photographs");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gimp",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Inkscape");
    $app->signal_connect('activate', sub {system "inkscape &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ Scalable\ Vector\ Graphics\ images");
    $app->set_image('Gtk2::Image'->new_from_icon_name("inkscape",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Draw");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-draw &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ drawings\,\ flow\ charts\ and\ logos\ by\ using\ Draw\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-draw",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("OpenSCAD");
    $app->signal_connect('activate', sub {system "openscad &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("openscad",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Viewnior");
    $app->signal_connect('activate', sub {system "viewnior &"});
    $app->set_property('tooltip_text', "Elegant\ Image\ Viewer");
    $app->set_image('Gtk2::Image'->new_from_icon_name("viewnior",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # MULTIMEDIA # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Multimedia");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-multimedia",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Cheese");
    $app->signal_connect('activate', sub {system "cheese &"});
    $app->set_property('tooltip_text', "Take\ photos\ and\ videos\ with\ your\ webcam\,\ with\ fun\ graphical\ effects");
    $app->set_image('Gtk2::Image'->new_from_icon_name("org\.gnome\.Cheese",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Ex\ Falso");
    $app->signal_connect('activate', sub {system "exfalso &"});
    $app->set_property('tooltip_text', "Edit\ tags\ in\ your\ audio\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("exfalso",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Qt\ V4L2\ test\ Utility");
    $app->signal_connect('activate', sub {system "qv4l2 &"});
    $app->set_property('tooltip_text', "Allow\ testing\ Video4Linux\ devices");
    $app->set_image('Gtk2::Image'->new_from_icon_name("qv4l2",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Quod\ Libet");
    $app->signal_connect('activate', sub {system "quodlibet\ \-\-run\ \-\-play\-file &"});
    $app->set_property('tooltip_text', "Listen\ to\,\ browse\,\ or\ edit\ your\ audio\ collection");
    $app->set_image('Gtk2::Image'->new_from_icon_name("quodlibet",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("VLC\ media\ player");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/vlc\ \-\-started\-from\-file &"});
    $app->set_property('tooltip_text', "Read\,\ capture\,\ broadcast\ your\ multimedia\ streams");
    $app->set_image('Gtk2::Image'->new_from_icon_name("vlc",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # NETWORK # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Network");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-internet",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Avahi\ SSH\ Server\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/bssh &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\-enabled\ SSH\ Servers");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Avahi\ VNC\ Server\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/bvnc &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\-enabled\ VNC\ Servers");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Chromium");
    $app->signal_connect('activate', sub {system "chromium &"});
    $app->set_property('tooltip_text', "Access\ the\ Internet");
    $app->set_image('Gtk2::Image'->new_from_icon_name("chromium",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Deluge");
    $app->signal_connect('activate', sub {system "deluge\-gtk &"});
    $app->set_property('tooltip_text', "Download\ and\ share\ files\ over\ BitTorrent");
    $app->set_image('Gtk2::Image'->new_from_icon_name("deluge",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Dropbox");
    $app->signal_connect('activate', sub {system "dropbox &"});
    $app->set_property('tooltip_text', "Dropbox\ is\ a\ free\ service\ that\ lets\ you\ bring\ your\ photos\,\ docs\,\ and\ videos\ anywhere\ and\ share\ them\ easily");
    $app->set_image('Gtk2::Image'->new_from_icon_name("dropbox",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("FileZilla");
    $app->signal_connect('activate', sub {system "filezilla &"});
    $app->set_property('tooltip_text', "Download\ and\ upload\ files\ via\ FTP\,\ FTPS\ and\ SFTP");
    $app->set_image('Gtk2::Image'->new_from_icon_name("filezilla",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Firefox");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/firefox\/firefox &"});
    $app->set_property('tooltip_text', "Browse\ the\ Web");
    $app->set_image('Gtk2::Image'->new_from_icon_name("firefox",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Mail\ Reader");
    $app->signal_connect('activate', sub {system "exo\-open\ \-\-launch\ MailReader &"});
    $app->set_property('tooltip_text', "Read\ your\ email");
    $app->set_image('Gtk2::Image'->new_from_icon_name("internet\-mail",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("networkmanager_dmenu");
    $app->signal_connect('activate', sub {system "networkmanager_dmenu &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("networkmanager_dmenu",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Web\ Browser");
    $app->signal_connect('activate', sub {system "exo\-open\ \-\-launch\ WebBrowser &"});
    $app->set_property('tooltip_text', "Browse\ the\ web");
    $app->set_image('Gtk2::Image'->new_from_icon_name("web\-browser",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # OFFICE # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Office");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-office",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Document\ Viewer");
    $app->signal_connect('activate', sub {system "evince &"});
    $app->set_property('tooltip_text', "View\ multi\-page\ documents");
    $app->set_image('Gtk2::Image'->new_from_icon_name("evince",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice");
    $app->signal_connect('activate', sub {system "libreoffice &"});
    $app->set_property('tooltip_text', "The\ office\ productivity\ suite\ compatible\ to\ the\ open\ and\ standardized\ ODF\ document\ format\.\ Supported\ by\ The\ Document\ Foundation\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-startcenter",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Base");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-base &"});
    $app->set_property('tooltip_text', "Manage\ databases\,\ create\ queries\ and\ reports\ to\ track\ and\ manage\ your\ information\ by\ using\ Base\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-base",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Calc");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-calc &"});
    $app->set_property('tooltip_text', "Perform\ calculations\,\ analyze\ information\ and\ manage\ lists\ in\ spreadsheets\ by\ using\ Calc\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-calc",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Draw");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-draw &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ drawings\,\ flow\ charts\ and\ logos\ by\ using\ Draw\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-draw",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Impress");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-impress &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ presentations\ for\ slideshows\,\ meeting\ and\ Web\ pages\ by\ using\ Impress\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-impress",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Math");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-math &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ scientific\ formulas\ and\ equations\ by\ using\ Math\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-math",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("LibreOffice\ Writer");
    $app->signal_connect('activate', sub {system "libreoffice\ \-\-writer &"});
    $app->set_property('tooltip_text', "Create\ and\ edit\ text\ and\ graphics\ in\ letters\,\ reports\,\ documents\ and\ Web\ pages\ by\ using\ Writer\.");
    $app->set_image('Gtk2::Image'->new_from_icon_name("libreoffice\-writer",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # SETTINGS # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Settings");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-accessories",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("File\ Manager");
    $app->signal_connect('activate', sub {system "thunar\-settings &"});
    $app->set_property('tooltip_text', "Configure\ the\ Thunar\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("system\-file\-manager",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Network\ Connections");
    $app->signal_connect('activate', sub {system "nm\-connection\-editor &"});
    $app->set_property('tooltip_text', "Manage\ and\ change\ your\ network\ connection\ settings");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-system\-network",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("networkmanager_dmenu");
    $app->signal_connect('activate', sub {system "networkmanager_dmenu &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("networkmanager_dmenu",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Preferred\ Applications");
    $app->signal_connect('activate', sub {system "exo\-preferred\-applications &"});
    $app->set_property('tooltip_text', "Preferred\ Applications\ \(Web\ Browser\,\ Mail\ Reader\ and\ Terminal\ Emulator\)");
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop\-default\-applications",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # SYSTEM # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("System");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("applications\-system",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Avahi\ Zeroconf\ Browser");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/avahi\-discover &"});
    $app->set_property('tooltip_text', "Browse\ for\ Zeroconf\ services\ available\ on\ your\ network");
    $app->set_image('Gtk2::Image'->new_from_icon_name("network\-wired",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Bulk\ Rename");
    $app->signal_connect('activate', sub {system "\/usr\/lib\/Thunar\/ThunarBulkRename &"});
    $app->set_property('tooltip_text', "Rename\ Multiple\ Files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("Thunar",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Color\ Profile\ Viewer");
    $app->signal_connect('activate', sub {system "gcm\-viewer &"});
    $app->set_property('tooltip_text', "Inspect\ and\ compare\ installed\ color\ profiles");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gnome\-color\-manager",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("GNOME\ System\ Monitor");
    $app->signal_connect('activate', sub {system "gnome\-system\-monitor &"});
    $app->set_property('tooltip_text', "View\ current\ processes\ and\ monitor\ system\ state");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-system\-monitor",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("GParted");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/gparted_polkit &"});
    $app->set_property('tooltip_text', "Create\,\ reorganize\,\ and\ delete\ partitions");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gparted",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Hardware\ Locality\ lstopo");
    $app->signal_connect('activate', sub {system "lstopo &"});
    $app->set_property('tooltip_text', "Show\ hardware\ topology");
    $app->set_image('Gtk2::Image'->new_from_icon_name("lstopo",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Htop");
    $app->signal_connect('activate', sub {system "urxvt\ \-e\ \'htop\' &"});
    $app->set_property('tooltip_text', "Show\ System\ Processes");
    $app->set_image('Gtk2::Image'->new_from_icon_name("htop",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Manage\ Printing");
    $app->signal_connect('activate', sub {system "\/usr\/bin\/xdg\-open\ http\:\/\/localhost\:631\/ &"});
    $app->set_property('tooltip_text', "CUPS\ Web\ Interface");
    $app->set_image('Gtk2::Image'->new_from_icon_name("cups",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Settings");
    $app->signal_connect('activate', sub {system "gnome\-control\-center\ \-\-overview &"});
    $app->set_image('Gtk2::Image'->new_from_icon_name("preferences\-system",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("System\ Log");
    $app->signal_connect('activate', sub {system "gnome\-system\-log &"});
    $app->set_property('tooltip_text', "View\ or\ monitor\ system\ log\ files");
    $app->set_image('Gtk2::Image'->new_from_icon_name("logview",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("System\ Monitor");
    $app->signal_connect('activate', sub {system "gnome\-system\-monitor &"});
    $app->set_property('tooltip_text', "View\ current\ processes\ and\ monitor\ system\ state");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-system\-monitor",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Terminal");
    $app->signal_connect('activate', sub {system "gnome\-terminal &"});
    $app->set_property('tooltip_text', "Use\ the\ command\ line");
    $app->set_image('Gtk2::Image'->new_from_icon_name("utilities\-terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Terminator");
    $app->signal_connect('activate', sub {system "terminator &"});
    $app->set_property('tooltip_text', "Multiple\ terminals\ in\ one\ window");
    $app->set_image('Gtk2::Image'->new_from_icon_name("terminator",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Thunar\ File\ Manager");
    $app->signal_connect('activate', sub {system "thunar &"});
    $app->set_property('tooltip_text', "Browse\ the\ filesystem\ with\ the\ file\ manager");
    $app->set_image('Gtk2::Image'->new_from_icon_name("Thunar",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("urxvt");
    $app->signal_connect('activate', sub {system "urxvt &"});
    $app->set_property('tooltip_text', "An\ unicode\ capable\ rxvt\ clone");
    $app->set_image('Gtk2::Image'->new_from_icon_name("terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("urxvt\ \(client\)");
    $app->signal_connect('activate', sub {system "urxvtc &"});
    $app->set_property('tooltip_text', "An\ unicode\ capable\ rxvt\ clone\ client\ for\ urxvtd");
    $app->set_image('Gtk2::Image'->new_from_icon_name("terminal",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("urxvt\ \(tabbed\)");
    $app->signal_connect('activate', sub {system "urxvt\-tabbed &"});
    $app->set_property('tooltip_text', "An\ unicode\ capable\ and\ tabbed\ rxvt\ clone");
    $app->set_image('Gtk2::Image'->new_from_icon_name("terminal",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    # # # # # # # # # # # # # # # # # # # # MENUTRAY # # # # # # # # # # # # # # # # # # # # 
{
    my $apps = 'Gtk2::Menu'->new;
    my $cat = 'Gtk2::ImageMenuItem'->new("Menutray");
    $cat->set_image('Gtk2::Image'->new_from_icon_name("preferences\-desktop",q{menu}));
{
    my $app = 'Gtk2::ImageMenuItem'->new("Config");
    $app->signal_connect('activate', sub {system "geany\ \\\/home\\\/bugsbunny\\\/\\\.config\\\/menutray\\\/config\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ configuration\ file");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Menu");
    $app->signal_connect('activate', sub {system "geany\ \\\/home\\\/bugsbunny\\\/\\\.config\\\/menutray\\\/menu\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ menu\ file\ for\ inspection");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $apps->append($app);
}
{
    my $app = 'Gtk2::ImageMenuItem'->new("Schema");
    $app->signal_connect('activate', sub {system "geany\ \\\/home\\\/bugsbunny\\\/\\\.config\\\/menutray\\\/schema\\\.pl &"});
    $app->set_property('tooltip_text', "Open\ the\ schema\ file\ to\ customize\ the\ menu");
    $app->set_image('Gtk2::Image'->new_from_icon_name("gtk\-edit",q{menu}));
    $apps->append($app);
}
    $cat->set_submenu($apps);
    $menu->append($cat);
}

    $menu->append('Gtk2::SeparatorMenuItem'->new);
{
    my $regenerate = 'Gtk2::ImageMenuItem'->new("Regenerate");
    $regenerate->set_property('tooltip_text', "Regenerate\ this\ menu\.");
    $regenerate->set_image('Gtk2::Image'->new_from_icon_name("gtk\-refresh",q{menu}));
    $regenerate->signal_connect('activate', sub {system "\/usr\/bin\/perl\ \\\/usr\\\/bin\\\/menutray\ \-i\ \-C\ \\\/home\\\/bugsbunny\\\/\\\.config\\\/menutray\\\/config\\\.pl\ \-S\ \\\/home\\\/bugsbunny\\\/\\\.config\\\/menutray\\\/schema\\\.pl\ \-o\ \\\/home\\\/bugsbunny\\\/\\\.config\\\/menutray\\\/menu\\\.pl &"; 'Gtk2'->main_quit});
    $menu->append($regenerate);
}
{
    my $quit = 'Gtk2::ImageMenuItem'->new("Exit");
    $quit->set_property('tooltip_text', "Close\ this\ application\.");
    $quit->set_image('Gtk2::Image'->new_from_icon_name("exit",q{menu}));
    $quit->signal_connect('activate', sub { Gtk2->main_quit });
    $menu->append($quit);
}
    $menu->show_all;
    return 1;
}
'Gtk2'->main;
